# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:23
from __future__ import unicode_literals

from django.db import migrations

import csv


def add_item_rater_data_info(apps, schema_editor):
    Item = apps.get_model("movieratings", "Item")
    Rater = apps.get_model("movieratings", "Rater")
    Data = apps.get_model("movieratings", "Data")

    with open("item.csv") as open_file:
        item_info = csv.reader(open_file, delimiter="|")
        for row in item_info:
            Item.objects.create(id=row[0],title=row[1],release_date=row[2],video_release_date=row[3],
                                imdb_url=row[4],unknown=row[5],action=row[6],adventure=row[7],
                                animation=row[8],childrens=row[9],comedy=row[10],crime=row[11],
                                documentary=row[12],drama=row[13],fantasy=row[14],film_noir=row[15],
                                horror=row[16],musical=row[17],mystery=row[18],romance=row[19],
                                sci_fi=row[20],thriller=row[21],war=row[22],western=row[23])


    with open("rater.csv") as open_file:
        rater_info = csv.reader(open_file, delimiter="|")
        for row in rater_info:
            Rater.objects.create(id=row[0],age=row[1],gender=row[2],occupation=row[3],zip_code=row[4])

    with open("data.csv") as open_file:
        data_info = csv.reader(open_file, delimiter="\t")
        for row in data_info:
            rater = Rater.objects.get(id=row[0])
            item = Item.objects.get(id=row[1])
            Data.objects.create(rater=rater,item=item,rating=row[2],time_stamp=row[3])


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0002_auto_20161006_2037'),
    ]

    operations = [
        migrations.RunPython(add_item_rater_data_info)
    ]
