# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0002_auto_20161006_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='rater_id',
            new_name='rater',
        ),
    ]
